set(SDL_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}")
set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/SDL2.lib" "${CMAKE_CURRENT_LIST_DIR}/SDL2main.lib")



add_library(SDL2_RUNTIME SHARED IMPORTED)


set_target_properties(SDL2_RUNTIME PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/SDL2/SDL2.dll")
set_target_properties(SDL2_RUNTIME PROPERTIES IMPORTED_IMPLIB "${CMAKE_CURRENT_SOURCE_DIR}/SDL2/SDL2.lib")


