

set(SDL_INCLUDE_DIRS "{CMAKE_CURRENT_LIST_DIR}")


if(${CMAKE_SIZEOF_VOID_P} MATCHES 8)
	set(SDL2_LIBRARIES "{$CMAKE_CURRENT_LIST_DIR}/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/SDL2main.lib"; "${CMAKE_CURRENT_LIST_DIR}/SDL2.dll")


	string(STRIP "${SDL2_LIBRARIES}" SDL_LIBRARIES)